[library.ibex]
location = /workspace/scratch/b66bbe7970f7/ibex-ihp-sg13g2-fullchip/third_party/ibex
sync-uri = /workspace/scratch/b66bbe7970f7/ibex-ihp-sg13g2-fullchip/third_party/ibex
sync-type = local
auto-sync = true

[library.ibex_ihp]
location = /workspace/scratch/b66bbe7970f7/ibex-ihp-sg13g2-fullchip
sync-uri = /workspace/scratch/b66bbe7970f7/ibex-ihp-sg13g2-fullchip
sync-type = local
auto-sync = true

